import type { AnyPrimitive } from "@aiet/schema";
import { describe, expect, it } from "vitest";
import { BuildOrchestrator } from "../src/orchestrator";

describe("BuildOrchestrator", () => {
  const basePrimitive: AnyPrimitive = {
    id: "ent_01H00000000000000000000001",
    schema_version: "1.0.0",
    type: "organization",
    name: "System",
    description: "System entity",
    sensitivity: "public",
    volatility: "low",
    activation: "always_on",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    last_verified: "2026-01-01T00:00:00Z",
  } as unknown as AnyPrimitive;

  const basePrimitive2: AnyPrimitive = {
    ...basePrimitive,
    id: "ent_01H00000000000000000000002",
    name: "System 2",
    description: "Another system entity",
  } as unknown as AnyPrimitive;

  it("same logical inputs in different input order => same manifest source hash and UP_TO_DATE", () => {
    const orchestrator = new BuildOrchestrator();
    const result1 = orchestrator.build([basePrimitive, basePrimitive2]);
    expect(result1.status).toBe("COMPLETED");
    expect(result1.is_incremental).toBe(false);

    const result2 = orchestrator.build(
      [basePrimitive2, basePrimitive],
      undefined,
      result1.manifest,
    );
    expect(result2.status).toBe("UP_TO_DATE");
    expect(result2.is_incremental).toBe(true);
    expect(result1.manifest.source_aggregate_hash).toBe(result2.manifest.source_aggregate_hash);
  });

  it("same ID with changed content => different source hash and rebuild", () => {
    const orchestrator = new BuildOrchestrator();
    const result1 = orchestrator.build([basePrimitive]);
    expect(result1.status).toBe("COMPLETED");

    const changedPrimitive = { ...basePrimitive, description: "Changed description" };
    const result2 = orchestrator.build([changedPrimitive], undefined, result1.manifest);

    expect(result2.status).toBe("COMPLETED");
    expect(result2.is_incremental).toBe(false);
    expect(result1.manifest.source_aggregate_hash).not.toBe(result2.manifest.source_aggregate_hash);
  });

  it("a primitive excluded/demoted by budget still changes source hash", () => {
    const orchestrator = new BuildOrchestrator();

    const largePrimitive: AnyPrimitive = {
      id: "dir_01H00000000000000000000003",
      schema_version: "1.0.0",
      statement: "A".repeat(1000),
      enforcement: "soft",
      domain: "global_style",
      sensitivity: "public",
      volatility: "low",
      activation: "always_on",
      created_at: "2026-01-01T00:00:00Z",
      updated_at: "2026-01-01T00:00:00Z",
      last_verified: "2026-01-01T00:00:00Z",
    } as unknown as AnyPrimitive;

    const options = { max_tier0_budget: 50 };
    const resultWithoutDrop = orchestrator.build([basePrimitive], options);

    // Add large primitive that will be demoted to tier1
    const resultWithDrop = orchestrator.build(
      [basePrimitive, largePrimitive],
      options,
      resultWithoutDrop.manifest,
    );

    expect(resultWithDrop.status).toBe("COMPLETED");
    expect(resultWithDrop.is_incremental).toBe(false);
    expect(resultWithDrop.manifest.tier1_primitive_ids).toContain(largePrimitive.id);
    expect(resultWithoutDrop.manifest.source_aggregate_hash).not.toBe(
      resultWithDrop.manifest.source_aggregate_hash,
    );
  });

  it("prior manifest generated by orchestration matches the hash used for incremental detection", () => {
    const orchestrator = new BuildOrchestrator();
    const result1 = orchestrator.build([basePrimitive]);

    // Using the same orchestrator instance and same input, should trigger incremental build
    // This implicitly proves the manifest hash matches the detection hash.
    const result2 = orchestrator.build([basePrimitive], undefined, result1.manifest);

    expect(result2.status).toBe("UP_TO_DATE");
    expect(result2.is_incremental).toBe(true);
    expect(result2.manifest).toBe(result1.manifest);
  });
});
